# application: ist-rooms
# version: 1
runtime: python27
api_version: 1
threadsafe: true

# [START handlers]
handlers:
# - url: /
#   static_files: index.html
#   upload: index.html

- url: /.*
  script: main2.app
# [END handlers]

# [START libraries] If use any
# libraries:
# - name: webapp2
#   version: latest
# - name: jinja2
#   version: latest
# [END libraries]
